name: Docker Image CI

on:
  push:
    branches: [ 5.6_homer ]

  workflow_dispatch:

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials for deploying to ECR
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set Docker Tag Var
        id: vars
        run: echo ::set-output name=VERSION::$(git branch --show-current)-$(git rev-parse --short HEAD)

    - name: Build and push the Squidex Docker Image
      run: make deploy

     - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.vars.outputs.docker_tag }}
          release_name: New Squidex Docker Image in ECR
          draft: false
          prerelease: false
